apiVersion: v1

kind: Secret

metadata:
  name: backend-secret
  namespace: workflow-builder

type: Opaque

stringData:
  JWT_SECRET: "cc77e87cdecf71d57217488dbf8deda596a2f5bbd8bd0f3688137ab8b908f2e9"

  DATABASE_URL: "postgresql://admin:admin123@postgres-service:5432/workflow_builder"