apiVersion: v1
kind: ConfigMap

metadata:
  name: frontend-config
  namespace: workflow-builder

data:
  config.js: |
    window.APP_CONFIG = {
      API_URL: "http://backend-service:5001/api",
    };